### ISSUE TITLE
No Ability to Add Custom Metrics/Controllers To Admin Context

### ISSUE THREAD

**Issue by terussell85** [spring-projects/spring-xd#1300]
I've created a module with a custom Metric, Handler and Repository patterned after the AggregateCounter but then it appears that there doesn't seem to be a way to add anything to the Admin Context.

The diagram at https://github.com/spring-projects/spring-xd/wiki/Extending-XD shows the Plugin Context as a sibling to the Admin Context which seems to verify my fears.

It would be convenient to be able to add custom Metrics/Controllers/Repositories into the Admin Context so that they can be accessed through the same REST api as the other Metrics.

**Comment by ericbottard** [comment]
I've created https://jira.spring.io/browse/XD-2705 to track this in JIRA.
