### ISSUE TITLE
Unable to run Groovy script from sink 

### ISSUE THREAD

**Issue by sridharpaladugu** [spring-projects/spring-xd#1395]
I am unable to run embedded groovy script in the sink definition file. The code is as pated below.
Further investigation and help from Thomos Risberg identified some jars are missing in 1.0.3 release.
I have to add the below jars to xd/lib to make the script to run without errors.

spring-xd-extension-script-1.0.3.RELEASE.jar
spring-integration-groovy-4.0.2.RELEASE.jar
spring-integration-scripting-4.0.2.RELEASE.jar

Actual script for testing:
=================
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:task="http://www.springframework.org/schema/task"
	xmlns:int="http://www.springframework.org/schema/integration"
	xmlns:int-hadoop="http://www.springframework.org/schema/integration/hadoop"
	xmlns:hdp="http://www.springframework.org/schema/hadoop"
	xmlns:int-groovy="http://www.springframework.org/schema/integration/groovy"
	xsi:schemaLocation="http://www.springframework.org/schema/integration http://www.springframework.org/schema/integration/spring-integration.xsd
		http://www.springframework.org/schema/integration/hadoop http://www.springframework.org/schema/integration/hadoop/spring-integration-hadoop.xsd
		http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
		http://www.springframework.org/schema/task http://www.springframework.org/schema/task/spring-task.xsd
		http://www.springframework.org/schema/hadoop http://www.springframework.org/schema/hadoop/spring-hadoop.xsd
		http://www.springframework.org/schema/integration/groovy http://www.springframework.org/schema/integration/groovy/spring-integration-groovy.xsd">
		
	 <hdp:configuration register-url-handler="false"
                properties-location="${xd.config.home}/hadoop.properties">
                fs.defaultFS=${fsUri}
        </hdp:configuration>
        <hdp:file-system />
        <hdp:resource-loader />
        <bean id="fsh" class="org.springframework.data.hadoop.fs.FsShell">
                <constructor-arg ref="hadoopConfiguration" />
                <constructor-arg ref="hadoopFs" />
        </bean>
        <import resource="../../../common/script-variable-generator.xml"/>
        <int:channel id="input" />
        <int:service-activator output-channel="nullChannel" input-channel="input">
                <int-groovy:script>
                        <int-groovy:variable name="hadoopConfiguration" ref="hadoopConfiguration" />
                        <int-groovy:variable name="hadoopFs" ref="hadoopFs" />
                        <int-groovy:variable name="hadoopResourceLoader" ref="hadoopResourceLoader" />
                        <int-groovy:variable name="srcDirectory" value="${srcDirectory}" />
                        <int-groovy:variable name="targetDirectory" value="${targetDirectory}" />
                        <int-groovy:variable name="targetFilename" value="${targetFilename}" />
                        
                        println "merge *.avro files in ${srcDirectory} to one file in  ${targetDirectory}"
                        try {
                                println "merging files"
                                fsh.getmerge(srcDirectory, targetFilename)
                                fsh.mv(targetFilename, targetDirectory)
                        } catch(Exception e) {
                                println e
                        }
                </int-groovy:script>
        </int:service-activator>

</beans>

**Comment by garyrussell** [comment]
If this is a custom module, you need to add `runtime(project(":spring-xd-extension-script"))` to your gradle dependencies; the others will be pulled in transitively into your module/lib directory.

We don't want to bloat the xd/lib directory with every possible jar any possible module might need.

**Comment by trisberg** [comment]
Wouldn't that require your custom module to be part of the spring-xd build?

Maybe try adding a dependency to:

{code}
<dependency>
    <groupId>org.springframework.xd</groupId>
    <artifactId>spring-xd-extension-script</artifactId>
    <version>1.0.3.RELEASE</version>
</dependency>
{code}

**Comment by garyrussell** [comment]
Yes, @trisberg , of course, sorry I just meant he should add the jar as a dep. I edited my comment.

**Comment by dturanski** [comment]
See https://github.com/spring-projects/spring-xd-samples/tree/master/groovy-script-sink

**Comment by sridharpaladugu** [comment]
Hi Garry
I have moved the jars to module/lib folder. For now that is working. Thank you.
