### ISSUE TITLE
Cleanup developer build and distribution build wiki docs

### ISSUE THREAD

**Issue by parikhkc** [spring-projects/spring-xd#160]
For people building XD from git clone we don't need them to run zipXD and distZip all the time. Clean up instructions on this wiki ->  https://github.com/SpringSource/spring-xd/wiki/Building-Spring-XD

**Comment by sabbyanandan** [comment]
This is already captured in [Building-Spring-XD](http://docs.spring.io/spring-xd/docs/1.2.1.RELEASE/reference/html/#building-spring-xd) section.
