### ISSUE TITLE
JDBC Oracle support

### ISSUE THREAD

**Issue by khoanguyen123** [spring-projects/spring-xd#1603]
I have created the DDL to support Oracle backend. Please consider adding them to Spring XD
Below are the contents of the DDL scripts:

### registry-schema-oracle.sql:
----------------------------------
CREATE TABLE XD_JOB_REGISTRY (
        JOB_NAME VARCHAR2(100) NOT NULL,
        IS_INCREMENTABLE VARCHAR2(10) NOT NULL,
        IS_RESTARTABLE VARCHAR2(10) NOT NULL
);
CREATE TABLE XD_JOB_REGISTRY_STEP_NAMES (
                JOB_NAME VARCHAR2(100) NOT NULL,
                STEP_NAME VARCHAR2(250) NOT NULL
);

### registry-schema-drop-oracle.sql:
-----------------------------------------
DROP TABLE XD_JOB_REGISTRY;
DROP TABLE XD_JOB_REGISTRY_STEP_NAMES;

**Comment by ilayaperumalg** [comment]
Thanks @khoanguyen123. I have added the script to the appropriate package and added the required configurations into config (servers.yml):  e569c11254ba92dd7bb43ad71e926e5967c14899
