### ISSUE TITLE
Redis bus header customization not working as expected

### ISSUE THREAD

**Issue by akhtet** [spring-projects/spring-xd#1643]
If my understanding is correct, there was a feature introduced in https://jira.spring.io/browse/XD-2047 so that we can make Redis bus carry custom headers which are set by custom modules. As such, I'm expecting Redis bus to carry all headers produced by the build-in Spring XD modules.

If I deploy a stream with FILE source and print out headers in the next module, i.e.

    stream create --name myevents --definition "file --dir=[path] --ref=false ... --outputType=text/plain | script --script=file://[path-to]/printHeaders.groovy | log" --deploy

Using Local bus, the following headers are received.

    timestamp, id, file_originalFile, contentType, file_name

Using Redis bus, the following headers are received.

    timestamp, id, contentType

Does this suggest that Redis did not carry over headers having underscore _  as part of the name? Even if I explicitly define a header name such as "file_name" in servers.yml, this header is not carried over in Redis bus.

**Comment by garyrussell** [comment]
Sorry for the delay; I have been traveling.

Your understanding is correct; headers appearing in `servers.yml` under

    xd:
      messagebus:
        redis:
          headers:

 should be transferred by the bus. Can you show your servers.yml config? Did you restart the container after changing the config?

**Comment by akhtet** [comment]
Hi @garyrussell 

I got around the problem using rabbitmq bus, so I haven't tested this problem using redis bus again.

But if you still want information about this, the problem with redis bus was that it was not carrying over any headers with an underscore in the name. (Or at least I suspect that was the problem.)

My servers.yml looked pretty ordinary, just like this.

    redis:
      headers:
        file_name, raw_delimiter

And yes, the containers and xd-admin were restarted.

**Comment by garyrussell** [comment]
Sorry that it took me so long to look at this but it's working fine for me:

    xd:>stream create foo --definition "time \
        | header-enricher \
             --headers='{\"foo_bar\":\"payload.charAt(0)\", \"baz_qux\":\"payload.charAt(1)\"}' \
        | log --expression=#this" --deploy

console:

>2015-12-07T16:11:43-0500 1.3.0.RELEASE INFO inbound.foo.1-redis:queue-inbound-channel-adapter1 sink.foo - GenericMessage [payload=2015-12-07 16:11:43, headers={baz=0, id=d8abcceb-96fd-d7f4-1d5d-ae3388f8a34b, foo_bar=2, timestamp=1449522703435}]

and redis `monitor`:

>1449522706.437462 [0 127.0.0.1:61692] "LPUSH" "queue.foo.1" "\xff\x03\x0bcontentType\x00\x00\x00\x0c\"text/plain\"\afoo_bar\x00\x00\x00\x03\"2\"\x03baz\x00\x00\x00\x03\"0\"2015-12-07 16:11:46"

As you can see, the headers are conveyed as expected (including headers with underscores).

I realize you switched to rabbit but let us know if you still see issues.
