### ISSUE TITLE
Missing v1.2.0.M1 and v1.2.0.RC1 Tags

### ISSUE THREAD

**Issue by nebhale** [spring-projects/spring-xd#1686]
The repository is still missing the `v1.2.0.M1` tag.  I'm trying to do a comparison to find out what has changed between it and the `v1.2.0.RC1` tag (which is also missing) and am not able to.  This is seriously affecting my ability to integrate the new versions of the product into our release.

**Comment by markpollack** [comment]
Sorry, has been very hectic.  Will make a tag, commit is

89471d9a71e31c75a0df4e3459d4be847d20b264

M

Sent from my iPhone

On Jun 4, 2015, at 6:11 AM, Ben Hale <notifications@github.com> wrote:

The repository is still missing the v1.2.0.M1 tag. I'm trying to do a
comparison to find out what has changed between it and the v1.2.0.RC1 tag
(which is also missing) and am not able to. This is seriously affecting my
ability to integrate the new versions of the product into our release.

—
Reply to this email directly or view it on GitHub
<https://github.com/spring-projects/spring-xd/issues/1686>.

**Comment by markpollack** [comment]
https://github.com/spring-projects/spring-xd/tree/v1.2.0.M1

and

https://github.com/spring-projects/spring-xd/tree/1.2.0.RC1
