### ISSUE TITLE
Spring Data Hibernate JPA jar files cannot get loaded

### ISSUE THREAD

**Issue by helloworld-2013** [spring-projects/spring-xd#1695]
I am using Spring XD 1.1.2.RELEASE and xd-singlenode container

I am writing custom processor which needs JPA, so I copy the extra jar files to enable JPA functionality into xd/lib:

hibernate-jpa-2.1-api-1.0.0.Final.jar
hibernate-entitymanager-4.3.9.Final.jar
hibernate-core-4.3.9.Final.jar
hibernate-commons-annotations-4.0.5.Final.jar
jandex-1.1.0.Final.jar
dom4j-1.6.1.jar
spring-orm-4.1.6.RELEASE.jar
spring-data-jpa-1.8.0.RELEASE.jar
spring-data-commons-1.10.0.RELEASE.jar
mysql-connector-java-5.1.35.jar

When I start xd-singlenode container then I encounter error: Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.HibernateException: Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set

I haven't even deployed my custom processor module.

Please help or is there any other way to enable Spring Hibernate JPA in Spring XD?

**Comment by markpollack** [comment]
Seems related to auto config kicking in, http://stackoverflow.com/questions/26548505/org-hibernate-hibernateexception-access-to-dialectresolutioninfo-cannot-be-null. Looks like it will help solve your issue

**Comment by helloworld-2013** [comment]
Thanks Mark, 

The link provides great guidance to me.

I created small jar file containing SpringBootApplication module and application.properties and copied it into xd/lib then I can start the xd-singlenode

I have to include my repositories and entities inside my custom processor spring-module.xml

I can use them in my custom processor now.
