### ISSUE TITLE
Would like to have S3 source / sink

### ISSUE THREAD

**Issue by helloworld-2013** [spring-projects/spring-xd#1809]
Hello Team,

I am not sure this is the correct medium to propose features, sorry if this is not.

Thanks.

**Comment by garyrussell** [comment]
Modules are (generally) based on Spring Integration components.

There is a Spring Integration extension project [spring-integration-aws](https://github.com/spring-projects/spring-integration-aws) which has S3 channel adapters.

The [Spring XD Reference Documentation](http://docs.spring.io/spring-xd/docs/1.3.0.M1/reference/html/#developing-modules-and-extensions) explains how to create a custom module.

If you'd be interested in contributing, see [the guidelines](https://github.com/spring-projects/spring-xd/blob/master/CONTRIBUTING.md).

**Comment by helloworld-2013** [comment]
Thanks. I would create custom modules for this.
