### ISSUE TITLE
Spring XD java config with jasypt encrypt lib

### ISSUE THREAD

**Issue by helloworld-2013** [spring-projects/spring-xd#1812]
Hello,

I am planning to use jasypt encrypt lib and reading application.properties from external location outside XD_HOME. Would it be possible?

And I have tried some POCs to load properties using normal Spring PropertyPlaceholderConfigurer and the property holder variable is still not set.

In my module config class 

@Configuration
@EnableIntegration
public class ModuleConfiguration {
    @Bean
    MessageChannel input() { return new DirectChannel(); }
    @Bean
    MessageChannel output() { return new DirectChannel(); }
    @Autowired
    TweetProcessor tweetProcessor;
    @Bean
    PropertyPlaceholderConfigurer propertyConfigurer() throws Exception {
        PropertyPlaceholderConfigurer propertyConfigurer = new PropertyPlaceholderConfigurer();
        propertyConfigurer.setLocation(new UrlResource("file:/apps/conf/application.properties"));
        return propertyConfigurer;
    }
}

And in my processor class

@MessageEndpoint
public class TweetProcessor {
    @Value("${filestorage.location}")
    private String tempFolder;
    @ServiceActivator(inputChannel = "input", outputChannel = "output")
    public Message process(Message message) {
        System.out.println(tempFolder);
        return message;
    }
}

I got error in xd after deploying my stream

Could not resolve placeholder 'filestorage.location' in string value "${filestorage.location}"

Thanks.

**Comment by helloworld-2013** [comment]
Thank you @garyrussell for the answer in http://stackoverflow.com/questions/33250684/spring-xd-java-config-doesnt-load-xml-resource

@PropertySource works , but i am planning to use jasypt encrypt lib , and load the properties using

    @Bean
    public EnvironmentStringPBEConfig environmentStringPBEConfig() {
        final EnvironmentStringPBEConfig environmentStringPBEConfig = new EnvironmentStringPBEConfig();
        environmentStringPBEConfig.setAlgorithm("PBEWithMD5AndDES");
        environmentStringPBEConfig.setPasswordEnvName("ENV_PWD");
        return environmentStringPBEConfig;
    }
    @Bean
    public StandardPBEStringEncryptor configurationEncryptor() {
        final StandardPBEStringEncryptor standardPBEStringEncryptor = new StandardPBEStringEncryptor();
        standardPBEStringEncryptor.setConfig(environmentStringPBEConfig());
        return standardPBEStringEncryptor;
    }
    @Bean
    public EncryptablePropertyPlaceholderConfigurer propertyConfigurer() throws Exception {
        final EncryptablePropertyPlaceholderConfigurer propertyConfigurer =
                new EncryptablePropertyPlaceholderConfigurer(configurationEncryptor());
        propertyConfigurer.setLocation(new UrlResource("file:/apps/conf/application.properties"));
        return propertyConfigurer;
    }

So far i am still getting Could not resolve placeholder 'filestorage.location' in string value "${filestorage.location}"

Thanks.

**Comment by artembilan** [comment]
Not sure if this will help you, but `PropertyPlaceholderConfigurer` is `BeanFactoryPostProcessor`, hence his `@Bean` method must be specific with `static` modifier. See this SO question and sample in its answer: http://stackoverflow.com/questions/33149198/spring-integration-spel-issues-with-annotation

**Comment by helloworld-2013** [comment]
Found the solution by using this: https://github.com/ulisesbocchio/jasypt-spring-boot

Using @EnableEncryptableProperties and @PropertySource inside my java config resolves the property placeholder in my processor with decrypted value.
