### ISSUE TITLE
Duplications on named channels and taps when the first processor has module.name.count > 1 

### ISSUE THREAD

**Issue by garciapd** [spring-projects/spring-xd#1850]
Hi, related by https://jira.spring.io/browse/XD-3100 and https://jira.spring.io/browse/XD-2115.

I have found two scenarios when the messages are still duplicated, when you add module.name.count > 1 at the first processor of a named channel or the first one in a tap.

**Environment:**
Spring XD 1.2.1.RELEASE
Running two spring-xd containers and one spring-xd admin
Kafka as transport layer with concurrency 10, minPartitionCount 10.

**First test set up** (Using a router as a sink and send the messages to a different named channels):
stream create f --definition "queue:foo > transform --expression=payload+'-foo' | log" 
stream create b --definition "queue:bar > transform --expression=payload+'-bar' | log"
stream deploy --name f --properties "module.transform.count=2"
stream deploy --name b --properties "module.transform.count=2"
stream create r --definition "time | router --expression=payload.contains('10')?'queue:foo':'queue:bar'" --deploy

Because of using kafka as a transport layer, these topics are created (that is ok):
b.0
f.0
queue_3Abar
queue_3Afoo
r.0

**First test result** (if I set up this using Redis as a transport layer works, fine, the issue is with kafka):
I was expecting to have 20 partitions in the topics queue_3Abar and queue_3Afoo, because the concurrency is 10 and the number of modules is 2 for the first processors (or are the scalation of the named channels managed in a different way?)
Also, I'm getting duplicates in both streams f and b. 
When you have count > 1 in any module, are not all these modules belonging to the same kafka consumer group?, it is working fine when I put the count > 1  in the processors that are not the first in the chain.

**The output of the logs are:**
2015-11-09T13:02:09+0000 1.2.1.RELEASE INFO pool-48-thread-1 sink.b - 2015-11-09 13:02:09-bar
2015-11-09T13:02:09+0000 1.2.1.RELEASE INFO pool-48-thread-1 sink.b - 2015-11-09 13:02:09-bar
2015-11-09T13:02:11+0000 1.2.1.RELEASE INFO pool-24-thread-1 sink.f - 2015-11-09 13:02:10-foo
2015-11-09T13:02:11+0000 1.2.1.RELEASE INFO pool-24-thread-1 sink.f - 2015-11-09 13:02:10-foo
2015-11-09T13:02:11+0000 1.2.1.RELEASE INFO pool-49-thread-1 sink.b - 2015-11-09 13:02:11-bar
2015-11-09T13:02:11+0000 1.2.1.RELEASE INFO pool-49-thread-1 sink.b - 2015-11-09 13:02:11-bar

--------

**Second test set up** (tapping the stream):
stream create f --definition "time | transform --expression=payload+'-foo' | log" --deploy
stream create b --definition "tap:stream:f.transform> transform --expression=payload+'-bar'  | log"
stream deploy --name b --properties "module.transform.count=2"

**Second test result:**
Duplication on the tapped stream even if I use kafka or redis as a transport layer

**The output of the logs are:**
2015-11-09T13:06:15+0000 1.2.1.RELEASE INFO pool-51-thread-1 sink.f - 2015-11-09 13:06:15-foo
2015-11-09T13:06:16+0000 1.2.1.RELEASE INFO pool-69-thread-1 sink.b - 2015-11-09 13:06:15-foo-bar
2015-11-09T13:06:16+0000 1.2.1.RELEASE INFO pool-69-thread-1 sink.b - 2015-11-09 13:06:15-foo-bar

Thanks.

**Comment by mbogoevici** [comment]
Hi, 

Thanks for reporting. We will try to fix this for 1.3.

**Comment by mbogoevici** [comment]
Please follow https://jira.spring.io/browse/XD-3613 for progress on fixing this for Kafka - it only refers to taps, but the solution should apply to named queues as well.

**Comment by garciapd** [comment]
Thanks Marius.

Also, I don't know if this is a bug or it is just that i'm not using the proper way, it is described in the description of the original message and also here: http://stackoverflow.com/questions/33611436/how-to-scale-up-named-channels-by-having-kafka-as-a-transport-layer

If the first processor of a stream that has a named channel as a source has counter > 1, and the transport layer is kafka. Shouldn't be creating as many partitions as counter * concurrency of the first module in the topic of the named channel?

**Comment by mbogoevici** [comment]
Hi Daniel,

Sorry, I focused on the duplication only in my answer:

The partitioning strategy is driven by the main stream and we have stayed away from dynamically repartitioning while the stream is running, as it brings with it a number of issues - it confuses partitioned streams, the new partitioning metadata is only propagated with a certain delay to producers and so on.

So the current behaviour is expected, adding taps will not increase the partition count. 

That being said, you will probably want to use multiple consumers with a concurrency of 10 on the tap - case in which you can overpartition the output of time to begin with by using the minPartitionCount property on the module output, as described here:

http://docs.spring.io/spring-xd/docs/current-SNAPSHOT/reference/html/#kafka-bus-partitions

Hope this helps,
Marius

**Comment by garciapd** [comment]
Ok understood that the partitioning is driven by the main stream, although I have set up the minPartitionCount in the module output (a router in that case) and I got an error:

Streams:
stream create f --definition "queue:foo > transform --expression=payload+'-foo' | log" 
stream create b --definition "queue:bar > transform --expression=payload+'-bar' | log"
stream deploy --name f --properties "module.transform.count=2"
stream deploy --name b --properties "module.transform.count=2"

stream create r --definition "time | router --expression=payload.contains('10')?'queue:foo':'queue:bar'"
stream deploy --name r --properties "module.router.producer.minPartitionCount=20"

The error is:
Caused by: java.lang.IllegalArgumentException: KafkaMessageBus does not support producer property: minPartitionCount for queue:bar.
	at org.springframework.xd.dirt.integration.bus.MessageBusSupport.validateProperties(MessageBusSupport.java:781) ~[spring-xd-messagebus-spi-1.2.1.RELEASE.jar:1.2.1.RELEASE]

Are these properties not applicable to the named channels?

**Comment by mbogoevici** [comment]
No, they need to be applied on the main stream.

**Comment by mbogoevici** [comment]
Ah, I see the issue now. Yes, this looks like a thing to fix for 1.3. Named channels should support this as well.

**Comment by garciapd** [comment]
Ok, so it is not working because even if I'm setting the property in the main stream ( because I'm setting this up in the router), it is connected to a named channel and the it doesn't like it?

**Comment by garciapd** [comment]
hehe ok, we were writing at the same time. Should I create the issue or are you going to add it?

**Comment by mbogoevici** [comment]
Please create a JIRA issue for it if you get a chance. Thank you :)

**Comment by garciapd** [comment]
https://jira.spring.io/browse/XD-3697

:)

**Comment by mbogoevici** [comment]
Cool, thanks!

**Comment by mbogoevici** [comment]
Hi Daniel,

Just in way of further clarification, for 1.3 we intend to fix the behaviour for named channels, in the sense of preventing duplication between the different instances of a module belonging to the same stream, while listening to a shared named channel. 

For Spring XD, in the case of Kafka, `queue:foo` behaves just like `topic:foo` and has publish-subscribe semantics. We do not intend to support multiple streams as competing consumers on a named channel with the Kafka bus. We should clarify this in the documentation and issue a warning. 

Cheers,
Marius

**Comment by garciapd** [comment]
Hi Marius, that is ok. Maybe it is worth to raise an exception if someone uses queue:foo rather than change the behaviour depending on the transport layer you choose, but you know better than me the implications.

Just to know if I'm understating properly. You mean that consumers from different streams won't be competing? (if that is the case it is ok). And if you create one stream which have several instances (count > 1) as a first processor, it will create (taliking in kafka terms) the same kafka consumer group for all of them, it means that in one stream you will have several modules reading from the same queue or topic and they will read the messages just once isn't it?

Thanks

**Comment by mbogoevici** [comment]
Hi Daniel,

Yes - we are debating whether to fail the deployment altogether or just issue a warning. 

Your interpretation is correct. Multiple streams listening to the same named channel  will receive the same messages, however, of the multiple consumers to a named queue at the beginning of a given stream, only one will receive a specific message (just like regular modules listening to a message bus topic). The current behaviour with taps/topics is due to a bug in the partitioning logic, which causes the modules to act as separate subscribers.

Hope this helps,
Marius

**Comment by garciapd** [comment]
Hi Marius, that is perfect, thanks for the explanation.

Cheers.

**Comment by mbogoevici** [comment]
Fixed via https://github.com/spring-projects/spring-xd/commit/e99f21c33fe7770c33346846c192d20c726b6ccb
