### ISSUE TITLE
Module is partitioned only if its count > 1, it is ok when Kafka is the message bus?

### ISSUE THREAD

**Issue by garciapd** [spring-projects/spring-xd#1852]
Hi, by reading the deployment manifest I have seen that one module is considered partitioned only if its count > 1, but in the case of using Kafka as a message bus, we are loosing the capability of ordering messages if the module's count is 1, by using Kafka we have several partitions also even if we have just one module deployed, and this can cause a serious of problem if you rely on Kafka to get the messages ordered by setting the message key.

It is not possible to set the property "module.*.producer.partitionKeyExpression" so messages are not keeping the order. The behavior is the one explained in the documentation, but IMHO it shouldn't be working like that.

Thanks.

**Comment by mbogoevici** [comment]
Daniel,

Can you describe your requirement more specifically? Do you want to be able to provide partitioning logic  even when the downstream module is count = 1 ?

**Comment by garciapd** [comment]
We communicate two modules using kafka as a message bus, and we can specify the number of partitions even if the module count =1, if we don't specify the partition strategy, the messages will be sent to random partitions (now it is using round robin). The partition strategy is using the message key, that only can be set up if the module count > 1.

So yes, I would like to be able to use the partitioning even with module count = 1.

We are using the feature that kafka offers you about ordering, by sending specific messages with the same key, you can guarantee that these messages are going to be sent to the same partition always (using the default system partitioner for instance).

In order to achieve this I was trying to use the kafka_messageKey property in the message header that Spring Integration Kafka should use, but I have seen an issue talking about don't mix the properties when kafka is transport layer and when using the sink, and I have seen by looking at the implementation that the messageKey is evaluated always using the partitionKeyExpression. So the only way to do it is by setting up the "module.*.producer.partitionKeyExpression" property I guess.

Cheers.

**Comment by mbogoevici** [comment]
Ok, thanks for the description. Makes sense. Added https://jira.spring.io/browse/XD-3702 for tracking.

**Comment by mbogoevici** [comment]
Fixed via https://github.com/spring-projects/spring-xd/commit/927554fee81bcf6a9adee059992a96bb2a54abff

**Comment by garciapd** [comment]
Cheers
