### ISSUE TITLE
Log configuration in tests

### ISSUE THREAD

**Issue by feugy** [spring-projects/spring-xd#1865]
I'm developping custom modules for Spring-XD, and doing some unit tests on them, using `SingleNodeApplication` and `SingleNodeIntegrationTestSupport` like explained in the [documentation](http://docs.spring.io/spring-xd/docs/current-SNAPSHOT/reference/html/#_create_an_in_container_test).

But I did not find any info on how to customize log configuration for this instances, to see my own log traces (or event `System.out.println`).

I've tried `config/xd-admin-logging.properties`, `config/xd-container-logging.properties`, `config/xd-singlenode-logging.properties`, and even `application.properties` with no results.

Any hint for that ?
Thanks a lot.

**Comment by ericbottard** [comment]
How are you running your tests? From an IDE or from gradle?
I assume your question relates to tuning your tests (you want your tests to assert things, not relying on logs to "see" if it works).
`System.out.println()` statements shoulds always produce something, for sure. As far as actual logs are concerned, you'll want to customize the loggers in the `src/test/resources` directory of the project that runs your tests I assume

**Comment by feugy** [comment]
This is a maven project (unfortunately, due to company restrictions), and I use IntelliJ.
It's the same behavior inside maven build and IntelliJ test run.

I don't want tu use output as part of my test, I just want to make some debugging by seing my outputs in the console.
I'm sure that the code is invoked (after using IntelliJ debugger), but no output visible in console.

I've tried to put the mentioned files inside `src/test/resources`, but no luck.
Inside my own code, I also use Apache common logging, like Spring XD does.

**Comment by ericbottard** [comment]
The fact that you don't even see `System.out.println` output is really disturbing. This must be a maven behavior (redirecting stdout). If you can fix this, maybe the rest will follow.

**Comment by feugy** [comment]
Ok, was all my fault: I did not see the slf4j warning in logs:

    SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
    SLF4J: Defaulting to no-operation (NOP) logger implementation

After adding slf4j-log4j12 jar to my pom, I've manage to configure logging by addind a regular `log4j.properties` file into `src\test\resources`.

Regarding `System.out.println`, that's ok, they are visible, seems I was really tired this particular day.
Sorry for annoyance !
