### ISSUE TITLE
Kafka message bus maxWait property is not set up

### ISSUE THREAD

**Issue by garciapd** [spring-projects/spring-xd#1888]
Hi, I have noticed that when I create large streams the latency grows a lot, and I have realized that the maxWait property is not used, at least I cannot see where it is used. After changing this property (attaching the debugger) from 100ms to 1ms, the latency decrease drastically.

The stream I have used to test that is:

stream create --name latencyTest2 --definition "http | header-enricher --headers={\"time\":\"T(java.lang.System).currentTimeMillis()\"}  | t1:transform --expression=payload+'0' | t2:transform --expression=payload+'0'| t3:transform --expression=payload+'0'| t4:transform --expression=payload+'0' | log --expression=T(java.lang.System).currentTimeMillis()-headers['time']" --deploy

With the maxWait property to 100ms is taking even seconds to get to the last step while with maxWait set to 1ms (or 10ms) is much much faster. I know that by setting this property to 1 or 10 will make the CPU to burn a little bit but we need that.

Is there a way to change the property? or it is a bug?

I only have seen that classes, where the maxWait is used to create the connections but it seems that is using the default value always, no the one through the config. 

Class KafkaMessageBus
line 400: configuration.setMaxWait(defaultMaxWait); (where the DefaultConnectionFactory is created and its configuration)

class DefaultConnectionFactory
line 152: DefaultConnectionFactory.this.configuration.getMaxWait() (when the connection is created, uses the maxWait but it has not been set up)

Thanks.

**Comment by mbogoevici** [comment]
Hi @garciapd,

Can you try setting the value in servers.yml - location is e.g. here: https://github.com/spring-projects/spring-xd/blob/master/config/servers.yml#L99. It applies to the entire bus, but I believe that this is what you want.

Cheers,
Marius

**Comment by garciapd** [comment]
Hi @mbogoevici , this is the property I have set up but with no effect, I don't see where this property is used.

**Comment by mbogoevici** [comment]
Should be set via `kafka-bus.xml`. It is a bug, probably. Can you create an issue for this, please?

Thank you.

**Comment by garciapd** [comment]
https://jira.spring.io/browse/XD-3740

Cheers.
