### ISSUE TITLE
How to set Parameters in Http-client Processor?

### ISSUE THREAD

**Issue by minilong** [spring-projects/spring-xd#1905]
I have a requirement to use http-client processor sending a post request with some parameters, but i didn't find anyway to do this. Could you help to advise on this?

**Comment by minilong** [comment]
For example, I want to send a post request: http://test.com/this/is/a/test?topic=test&content=hellow. How to set the "topic" and "content"?

**Comment by garyrussell** [comment]
If they are constant, them simply add them to the `--url` property:

    --url='''http://test.com/this/is/a/test?topic=test&content=hellow'''

If they are variables then you need to customize the processor, by adding `<uri-variable/>` elements to the outbound gateway...

    <int-http:uri-variable name="content" expression="someExpressionToCalculateContent"/>

e.g.

        <int-http:uri-variable name="content" expression="headers['content']"/>

and then put a variable placeholder in the url:

    --url='''http://test.com/this/is/a/test?topic=test&content={content}'''

**Comment by minilong** [comment]
@garyrussell Great thanks! It works!
And maybe others come across the same problem, here is my case.

I want to set the "content" parameter of JSON data, but the first 2 options all fails. The errors shown below.
```
2016-03-15T09:56:48+0800 1.3.1.RELEASE ERROR pool-19-thread-12 http.NettyHttpInboundChannelAdapter - Error sending message
org.springframework.messaging.MessageHandlingException: HTTP request execution failed for URI ['http://192.168.90.219:8189/tp/v1/input/warnEventsCollect/bill_warning_module'{\"msgId\":null,\"creationTime\":0,\"releaseTime\":1453174813665,\"expiryTime\":0,\"source\":null,\"warnWho\":\"c280802b-4b50-11e5-a89b-02514540cad1\",\"content\":null,\"topicName\":null}]; nested exception is java.lang.IllegalArgumentException: Map has no value for '\"msgId\"'
	at org.springframework.integration.http.outbound.HttpRequestExecutingMessageHandler.handleRequestMessage(HttpRequestExecutingMessageHandler.java:409) ~[spring-integration-http-4.2.5.RELEASE.jar:na]
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:99) ~[spring-integration-core-4.2.5.RELEASE.jar:na]
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:127) ~[spring-integration-core-4.2.5.RELEASE.jar:na]
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:116) ~[spring-integration-core-4.2.5.RELEASE.jar:na]

```

So I tried the third option to customize the procossor.
I created a stream,
`stream create --name myCallBack --definition "http | header-enricher --headers={\"topic\":\"'test'\",\"content\":\"payload.toString()\"} | http-client --url='''http://192.168.90.219:8189/tp/v1/input/warnEventsCollect/bill_warning_module?topic=test&content={content}''' | file" --deploy
`
And also modify the module configuration file "http-client.xml" as below,
```
<?xml version="1.0" encoding="UTF-8"?>
<beans:beans xmlns="http://www.springframework.org/schema/integration"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:beans="http://www.springframework.org/schema/beans"
	xmlns:int-http="http://www.springframework.org/schema/integration/http"
	xsi:schemaLocation="http://www.springframework.org/schema/beans
		http://www.springframework.org/schema/beans/spring-beans.xsd
		http://www.springframework.org/schema/integration
		http://www.springframework.org/schema/integration/spring-integration.xsd
		http://www.springframework.org/schema/integration/http
			http://www.springframework.org/schema/integration/http/spring-integration-http.xsd">

	<int-http:outbound-gateway id='http-client'
		request-channel='input' url-expression="${url}" http-method="${httpMethod}"
		expected-response-type='java.lang.String' charset='${charset}'
		reply-timeout='${replyTimeout}' reply-channel='output'
		mapped-request-headers="${mappedRequestHeaders}"
		mapped-response-headers="${mappedResponseHeaders}" >
		<int-http:uri-variable name="content" expression="headers['content']"/>
	</int-http:outbound-gateway>
	


	<channel id="output" />
	<channel id="input" />

</beans:beans>
```
And then enjoy yourself.

Again thanks @garyrussell !
