### ISSUE TITLE
Batch-job with parameters insert through REST -> shell&http

### ISSUE THREAD

**Issue by pentchomakov** [spring-projects/spring-xd#1910]
Hi guys,

[SpringXD] - Perhaps this is already possible, but I'm having trouble executing a batch job with new params through the shell. I'm trying to do: http post --target http://localhost:9393/jobs/executions?jobname=my-job-name --data {"key1":"value1", "key2":"value2",...,"keyn":"valuen"}. I can launch the job if I send dummy data, but it won't map to the params that the job is set to accept. That being said, if I manually launch the job through the admin-ui and add params one-by-one, there is no problem.

Thank you in advance for your help!

**Comment by mminella** [comment]
Two notes:
1. Why are you using that REST command directly and not using `xd:> job launch --name my-job-name --params {"key1":"value1","keyn":"valuen"}`?
2.  What is the endpoint you are trying to hit?  If you got that command from our documentation [here](http://docs.spring.io/spring-xd/docs/1.3.1.RELEASE/reference/html/#_launching_a_job), that is posting to the HTTP source of a stream definition.  Are you deploying the job as part of a stream or some other mechanism?

**Comment by pentchomakov** [comment]
1. I'm using the REST command because I'm testing the commands to later on implement it on a custom interface (AJAX calls).
2. I basically deployed a job that is suppose to run when it receives parameters, but be "dormant" otherwise.

**Comment by mminella** [comment]
Just looking at the controller, I'd expect this to work (I haven't verified):
```
xd:> http post --target http://localhost:9000/jobs/executions --data "{\"jobname\":\"my-job-name\", \"jobParameters\": {\"key1\":\"value1\"}}"
```

**Comment by pentchomakov** [comment]
From testing, you absolutely need to add the jobname at the end of the target as such: 
`xd:> http post --target http://localhost:9000/jobs/executions?jobname=my-job-name`
As for the data, I'm still getting the same error: "Error sending data %data% to %target%". Perhaps I'm missing something in my Java code; I retrieve the data with jobParameters();

Basically, I want to recreate RESTfully the process of launching a job and adding a param to it.

![image](https://cloud.githubusercontent.com/assets/11916376/15159154/1fd73d2a-16c1-11e6-8122-3f2bac5c7f9e.png)

**Comment by mminella** [comment]
Ok, I'm still working out how to make this work with our shell.  However, here is the `curl` command that works:
```
$ curl -X POST --data 'jobname=foo&jobParameters={"%2Bfoo(string)":"bar"}' http://localhost:9393/jobs/executions
```

**Comment by pentchomakov** [comment]
thank you very much, I figured my Ajax call from the curl command!
