### ISSUE TITLE
Log4J configuration for custom modules on XD

### ISSUE THREAD

**Issue by prateec** [spring-projects/spring-xd#1916]
Hi, 
Do we have any guide or pointers for How to configure and enable log4j to write logs for custom Spring Batch modules?
Currently, I am seeing log4j jar under xd/lib already. I am keeping the log4j.properties under xd.config.location and making the Spring Batch module to read from there. 
But the log files are not getting created!

Could you please suggest if anything needs to be added/configured in xd-singlenode-logback.groovy?

Many Thanks, 
Pratik

**Comment by garyrussell** [comment]
Sorry we didn't answer this - container logging is configured in the `xd/lib/xd-container-logback.groovy` or `xd/lib/xd-singlenode-logback.groovy`.

**Comment by prateec** [comment]
@garyrussell Thanks for your response. Could you also please respond to #1917 which is getting a bit urgent for us. 

Thanks,
Pratik
