### ISSUE TITLE
Creating a stream from XD shell with the same http port will throw an exception but not too clear what it is.

### ISSUE THREAD

**Issue by jaoki** [spring-projects/spring-xd#368]
Trivial but I took some time to figure out.
Creating a stream with the same http port will throw an exception but not too clear what it is.

```
xd:>stream list
  Stream Name  Stream Definition  Status
  -----------  -----------------  --------
  http1       http | log         deployed

xd:>stream create --definition "http | log" --name http2
19:02:12,799  WARN Spring Shell client.RestTemplate:524 - POST request for "http://localhost:9393/streams" resulted in 500 (Internal Server Error); invoking error handler
Command failed org.springframework.xd.rest.client.impl.SpringXDException: error occurred in message handler [moduleDeployer]
```

The message should be something like 'port is in use', instead of moduleDeployer.

**Comment by sabbyanandan** [comment]
Descriptive error message is added to the stacktrace:

> Caused by: org.jboss.netty.channel.ChannelException: Failed to bind to: 0.0.0.0/0.0.0.0:9000
> Caused by: java.net.BindException: Address already in use
