### ISSUE TITLE
Project import in Intellij IDEA

### ISSUE THREAD

**Issue by fbiville** [spring-projects/spring-xd#526]
I'm using IDEA 13.0.1 Ultimate and Spring XD test source files seems not included in the classpath, making it impossible to launch any tests from the IDE.

Am I the only with this configuration or facing this issue?

**Comment by sabbyanandan** [comment]
Following command allows importing (and testing) of Spring XD projects in Intellij:
```
./gradlew cleanIdea idea
```
If you're still facing any issues, we could reopen this.

**Comment by fbiville** [comment]
Sorry, last time I checked, it worked fine :)
