### ISSUE TITLE
Centralized deployment of scripts across containers

### ISSUE THREAD

**Issue by smishra** [spring-projects/spring-xd#931]
We have a scenario where we are running Spring-XD in distributed mode - using Yarn - across several machines. We heavily use Groovy based processors and in certain cases custom Java sink modules. Currently we have to manually copy these modules to all the machines where Spring-XD runs on. This is not only buggy but also a real management nightmare. Please provide a central way of deploying these modules similar to what Hadoop allows.

**Comment by sabbyanandan** [comment]
@smishra, @kalyanvgopal: We expose a REST-API to upload custom modules as explained in [custom module registration](http://docs.spring.io/spring-xd/docs/1.2.1.RELEASE/reference/html/#registering-a-module) section. There's also separate sections on creating custom [source](http://docs.spring.io/spring-xd/docs/1.2.1.RELEASE/reference/html/#creating-a-source-module), [processor](http://docs.spring.io/spring-xd/docs/1.2.1.RELEASE/reference/html/#creating-a-processor-module) and [sink](http://docs.spring.io/spring-xd/docs/1.2.1.RELEASE/reference/html/#creating-a-sink-module) modules. 

If you run into any other issues, please open an new ticket or engage with us in stackoverflow.
